#!/bin/bash

#If this is the first time you run the container, clone (get) PlexConnect, else update
if [ ! -f /PlexConnect/ATVSettings.cfg ]; then
  echo "*** Cloning PlexConnect ***"
  cd /
  git clone https://github.com/iBaa/PlexConnect.git
else
  echo "*** Updating PlexConnect ***"
  cd /PlexConnect
  git pull
fi

#If this is the first time, generate certificates
if [ ! -f /PlexConnect/assets/certificates/trailers.pem ]; then
  # Use the APP_CN environment variable or default to appletv.flickr.com (testing)
  APP_CN=${APP_CN:-appletv.flickr.com}

  echo "*** Generating certificates for ${APP_CN} ***"
  openssl req -new -nodes -newkey rsa:2048 -out ./trailers.pem -keyout ./trailers.key -x509 -days 7300 -subj "/C=US/CN=${APP_CN}"
  openssl x509 -in ./trailers.pem -outform der -out ./trailers.cer && cat ./trailers.key >> ./trailers.pem
  mv trailers.* /PlexConnect/assets/certificates
fi

echo "*** Setting userID and groupID ***"
chown -R $USERID:$GROUPID /PlexConnect

echo "*** Starting PlexConnect ***"
python /PlexConnect/PlexConnect.py
